### ISSUE TITLE
Allow force-wrapping of embedded resources in a list

### ISSUE THREAD

**Issue by passy** [wharris/dougrain#4]
I don't think the spec has a rule for this, but I could easily be wrong on this. Currently, when using `Document.embed`, you get a different data structure depending on whether you call it once or more often. If you iterate over, for example, a database result and want to provide a unified interface independent of the result length, you would have to have make a check like this on the server:

``` python
if len(result) == 1:
    doc.embed('rel', [result])
else:
    [doc.embed('rel', r) for r in result]
```

I'd like to have a flag on `embed` to always wrap the object in a list, even on the first call. What do you think?

**Comment by wharris** [comment]
The spec says the values of the `_embedded` object "are either a Resource Object or an
   array of Resource Objects.", just like with `_links`. I guess the spec has two representations for single links (and, by symmetry, embedded resources) to make the client code simpler for applications where a particular link relation always has a single link.

A document with a single `self` link seems more natural to me than one with an array of one `self` link:

``` json
{"_links": {"self": {"href": "https://github.com/wharris/dougrain/issues/4"}}}
```

vs

``` json
{"_links": {"self": [{"href": "https://github.com/wharris/dougrain/issues/4"}]}}
```

That said, I think you're right. There should be a way to specify that an embedded resource (or a link) is always wrapped in an array. Since [draft 4](http://tools.ietf.org/html/draft-kelly-json-hal-04) single CURIE definitions have been wrapped in an array, so Dougrain already does something similar.

I'll look at implementing this.

**Comment by wharris** [comment]
In commit 45d0387cb810aa1bc817250c0aa840db8200190d (on branch master), I've added an optional `wrap` argument to `Document.embed` (and `Document.add_link`) that will let you force-wrap the target.

You should now be able to do this:

``` python
[doc.embed('rel', r, wrap=True) for r in result]
```

Here, the embedded resources will be wrapped in an array even if there are zero or more `Document`s in `result`.

You can change the default by subclassing `Document`:

``` python
class WrappingDocument(dougrain.Document):
    def embed(self, rel, other, wrap=True):
        super(WrappingDocument, self).embed(rel, other, wrap=wrap)
```

**Comment by wharris** [comment]
I forgot to force-wrap the automatic links that are inserted for Draft 5 conformance. Commit d710762 fixes that oversight.

**Comment by passy** [comment]
@wharris Thank you so much. That is going to make my code a lot simpler. :beers:
